version: "3.8"
services:
  app:
    build: .
    container_name: springboot
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
